import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/providers/theme-provider'
import localFont from 'next/font/local'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
  
const blanka = localFont({
  src: '../fonts/Blanka-Regular.otf',
  display: 'swap',
  variable: '--font-blanka'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={  `${inter.variable} ${blanka.variable}` }>
      <ThemeProvider 
            attribute="class" 
            defaultTheme="dark" 
            enableSystem
          >
          { children }
          </ThemeProvider>
      </body>
    </html>
  )
}
